#!/system/bin/sh
## Author  	: AGCH
## Github  	: @alexgeorgchist
## 17.01.2023
## Thanks to @deadrabbit404

PROGNAME=${0##*/}
LOGODIR="/sdcard/t-ui/ascii"
LOGO="inf.txt"


#BRAND=`getprop ro.product.brand`
#MODEL=`getprop ro.product.model`
#CODENAME=`getprop ro.product.device`
#ANDROID_VERSION=`getprop ro.build.version.release`
#CPUARCH=`getprop ro.product.cpu.abi`
#CPUCORE=`grep -c "^processor" /proc/cpuinfo`
#CPUFREQ=`< /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq`
MEMTOTAL=`grep MemTotal /proc/meminfo | awk '{ print $2 }'`
MEMAVAIL=`grep MemAvail /proc/meminfo | awk '{ print $2 }'`
#ZRAM=`grep SwapTotal /proc/meminfo | awk '{ print $2 }'`
#KERNEL=`uname -r | cut -f 1 -d "/"`
#PATCH=`getprop ro.build.version.security_patch`
#DATA_ENCRYPTION=`getprop ro.crypto.state`

# Truncate those having 0 values from output of `uptime -p`
UPTIME=`uptime -p | sed "s/ 0 [^ ]*,//g" | sed "s/up //" | sed "s/week/нед/" | sed "s/days/д/" | sed "s/day/д/" | sed "s/hours/ч/" | sed "s/minutes/мин/"`
# The time has been up
BEENTIMEUP=`uptime -s`


#Read psalms for everydays
everyday_psalm () {
DIR="/storage/emulated/0//t-ui/script_texts"
TXT1="$DIR/numdate.txt"
TXT2="$DIR/numpsalm.txt"
if [[ ! -f $TXT1 ]] || [[ ! -f $TXT2 ]]
    then echo " !!! Надо вписать сегодняшную дату в numdate.txt ( подсказка: выполнить команду date +%j ) и номер сегодняшней кафизмы в numpsalm.txt в папке script_texts"
             echo 1 > $DIR/numdate.txt
             echo 1 > $DIR/numpsalm.txt
             exit 0
fi
LASTTIME=`cat $DIR/numdate.txt`
NOWTIME=`date +%j` #Number day of the year (001-365)
    let "RAZN = $NOWTIME - $LASTTIME"

LASTPSALM=`cat $DIR/numpsalm.txt`
    let "PSALM = $LASTPSALM + $RAZN"

if [ "$PSALM" -gt 20 ] # >20
    then let "PSALM = $PSALM - 20"
fi

echo $NOWTIME > $DIR/numdate.txt
echo $PSALM > $DIR/numpsalm.txt

    padding=16
    printf "   %${padding}s : %s\n"\
              "today" "$PSALM кафисма"
}


# !!! Read Psaltir
psaltir_papa_mama () {

BEGINDAYPAPA=66      # Day of the begin to read psaltir papa=66
BEGINDAYMAMA=116 # Day of the begin to read psaltir mama=116
DATENOW=`date +%j` #Number day of the year xxx-format

let "P = $DATENOW - $BEGINDAYPAPA"
let "M = $DATENOW - $BEGINDAYMAMA"

PREAD="$P" # How days from the begin to read
MREAD="$M" # How days from the begin to read

# Papa
if [ "$DATENOW" -ge "$BEGINDAYPAPA" ] && [ "$DATENOW" -le 85 ] # >=66 &&<=85
     then let "PREAD = $P + 1"
         elif [ "$DATENOW" -ge 86 ] && [ "$DATENOW" -le 105 ] # >=86 && <=105
             then let "PREAD = $P - 19" # $P - 1 + 20
                 elif [ "$DATENOW" -ge 106 ]
                     then let "X = $DATENOW - 365" && let "PREAD = $X - $BEGINDAYPAPA"
                         elif [ "$P" -eq -1 ] # = -1
                             then PREAD="zavtra"
fi
     
#Mama
if [ "$DATENOW" -ge "$BEGINDAYMAMA" ] && [ "$DATENOW" -le 135 ] # >=116 && <=135
     then let "MREAD = $M + 1"
         elif [ "$DATENOW" -ge 136 ] && [ "$DATENOW" -le 155 ] # >=136 && <=155
             then let "MREAD = $M - 19" # $P - 1 + 20
                 elif [ "$DATENOW" -ge 156 ] # >=156
                     then let "X = $DATENOW - 365" && let "MREAD = $X - $BEGINDAYMAMA"
                         elif [ "$M" -eq -1 ] # = -1
                             then MREAD="zavtra"
fi

padding=16
printf "   %${padding}s : %s\n"\
          "Papa psalms" "$PREAD"\
          "Mama psalms" "$MREAD"
                 
if [ "$PREAD" -ge 1 ] && [ "$P" -le 20 ]          
   then sleep 2 && sh /storage/emulated/0/t-ui/script/pokoypsaltir %
fi
if  [ "$MREAD" -ge 1 ] && [ "$M" -le 20 ]   
       then sleep 2 && sh /storage/emulated/0/t-ui/script/pokoypsaltir %
fi
}


# Determine SELinux status without root access
cat /sys/fs/selinux/enforce >/dev/null 2>&1
[ $? -eq 0 ] && SELINUX="Permissive" || SELINUX="Enforcing"


print_duble_line () {
    printf " =============================================="
    printf " \n"
}
    
print_logo () {
# Print distro ascii art logo
    cat "$LOGODIR/$LOGO"
}


get_public_ip () {
    ip=`curl -s ifconfig.me`
    ip=${ip:="<Unkown>"}
    echo "$ip"
    exit 0
}


print_info () {
# Print all the information
    padding=16
    printf "   %${padding}s : %s\n"\
        "Available" "$((MEMAVAIL/1024)) MiB"\
        "Total" "$((MEMTOTAL/1024)) MiB"\
        "Up time" "$BEENTIMEUP"\
        " " "$UPTIME"
#        printf "%${padding}s : %s\n" "Public IPv4" `get_public_ip`
}



# Script starts here

print_duble_line
print_logo
print_info
everyday_psalm
psaltir_papa_mama
print_duble_line







