#!/bin/sh

## MM - My Manager
## Author  	: AGCH ( thanks to EMA,Dedrabbit and guys )
## Github  	: @alexgeorgchist

##################################
##                              ##
##       ##   ##  ##   ##       ##
##   #   ### ###  ### ###   #   ##
##  ###  ## # ##  ## # ##  ###  ##
##   #   ##   ##  ##   ##   #   ##
##       ##   ##  ##   ##       ##
##                              ##
##################################

SCRIPTNAME=${0##*/}

## DIRECTORIES
HOME="/storage/emulated/0"
TUI="t-ui"
THEMES_LIST=("my_nethunter" "my_sharif" "aqua" "gf45" "yellow" "big_bold" "tomato_silver")
ZP=".zip"


## LINKS
LINK="https://github.com/alexgeorgchist/my_tui/raw/main/database"
#LINKSCRIPT="https://github.com/alexgeorgchist/my_tui/edit/main/database/scripts/"
SCRIPT="https://github.com/alexgeorgchist/my_tui/raw/main/database/script.zip"
LOGOS="https://github.com/alexgeorgchist/my_tui/raw/main/database/logos.zip"


## LABELS

print_header () {
    printf "%s\n" \
        "#######################################" \
        "#         $SCRIPTNAME - УСТАНОВЩИК ТЕМ         #" \
        "#######################################" 
	   printf " \n"
}

print_end () {
    printf " \n"
    printf "%s\n" \
        "======================================="\
        "      $SCRIPTNAME - Тема «$CHOSEN_THEME»        "\
        "  установлена.  ПЕРЕЗАГРУЗИТЕ  «T_UI».         " \
        "=============== THE END ================"
    
    printf " \n\n"
}


##SUBBLOCKS

show_help(){
 
	padding=-14
	print_header
	printf "%s\n" \
	    " :.: Как пользоваться:"\
        "     sh $SCRIPTNAME [-h, --help]"\
        "       [-l, --list]"\
        "       [1,2 или 3... до 7]"\
        "       [-v, --version]"

		
    printf " \n"
    printf "  %${padding}s %s\n" \
	    "От 1 до 7" "Установка темы n.1 (2,3 и т.д.)" \
        "-l, --list" "Показать доступные темы" \
        "-h, --help" "Справка по использованию" \
        "-v, --version" "Версия программы"
        
	printf " \n"
	printf "  %${padding}s %s\n" \
        " :.: Примечание:" \
        " Набрать mm далее выбранный аттрибут через пробел."
        
	exit 1
}


show_theme(){

	echo "Скрипт установки темы T-UÍ"
printf " \n"
echo " ##################################"
echo " ##                              ##"
echo " ##       ##   ##  ##   ##       ##"
echo " ##   #   ### ###  ### ###   #   ##"
echo " ##  ###  ## # ##  ## # ##  ###  ##"
echo " ##   #   ##   ##  ##   ##   #   ##"
echo " ##       ##   ##  ##   ##       ##"
echo " ##                              ##"
echo " ##################################"
	padding=-20
	printf " \n"
	printf "%s\n" \
	    " ---------------------------------- "\
        "             СПИСОК ТЕМ:         "

    LIST="1 2 3 4 5 6 7"
for NUM in $LIST
do
    echo "  $NUM. ${THEMES_LIST[$NUM -1]}" 
done

	printf "%s\n \n " \
	    " ---------------------------------- "    
	printf "%s\n " \
		":.: Для установки набрать: mm номер" \
		"   Пример: mm 4 [ загрузка yellow ] " \
	    " " \
		":.:   mm -h    ---- вызов справки"
		
    exit 1
}


version(){
	printf "%s\n" \
	          " " \
              " :.: MM - My Manager ( themes for t-ui )" \
	          " :.: Версия программы  v.1.06 от 28.04.22 "
	
	exit 1
}



## [123456789]|10|11|12|13)
## index=$(($1-1))   ##CHOSEN_THEME="{THEME_LIST[$index]}"


case "$1" in
    [1234567])
	index=$(($1 - 1))
	CHOSEN_THEME="${THEMES_LIST[$index]}"
        ;;
    -l|--list|%)
        show_theme
        ;;  
    -v|--version)
        version
        ;;
    -h|--help)
		show_help
        ;;
    *)
        printf " :.: Недействительный аттрибут.\n";sleep 1.0
        printf " \n"    
        show_help
        exit 1
        ;;
esac




## START PROG HERE

    print_header

    printf "\n\n :.:  Удаление папки t-ui ...  :.:"
    cd $HOME && rm -rf $TUI
    printf "\n\n ... УСПЕШНО.  ";sleep 2.0

    printf "\n\n :.:  Скачиваю файл установки из репозитория ...   :.:"
    cd $HOME && curl -LJO $LINK/$CHOSEN_THEME$ZP
    printf "\n\n ... УСПЕШНО.  "

    printf "\n\n :.:  Распаковываю архив  :.: \n\n";sleep 2.0  
    unzip -d $HOME $CHOSEN_THEME$ZP
    rm -rf $CHOSEN_THEME$ZP
    printf "\n\n ... УСПЕШНО.  :.:"

    printf "\n\n :.:  Скачиваю и добавляю скрипты sysinfo и chwf   :.: \n\n";sleep 2.0
    cd $HOME/$TUI && rm -rf script logos
    cd $HOME/$TUI && curl -LJO $SCRIPT
    cd $HOME/$TUI && curl -LJO $LOGOS
    unzip script.zip && unzip logos.zip
    rm -rf script.zip logos.zip
    printf "\n\n ... УСПЕШНО.  :.:"

## Добавляю строки в alias.txt
    echo "mm =sh /storage/emulated/0/mm %">>/storage/emulated/0/t-ui/alias.txt
    echo "mm -p=search -u https://github.com/alexgeorgchist/my_tui/tree/main/database">>/storage/emulated/0/t-ui/alias.txt
    echo "sysinfo=sh /sdcard/t-ui/script/sysinfo %">>/storage/emulated/0/t-ui/alias.txt
    echo "chwf=sh /sdcard//t-ui/script/chwf %">>/storage/emulated/0/t-ui/alias.txt
    echo "aliases=cat /sdcard/t-ui/alias.txt">>/storage/emulated/0/t-ui/alias.txt
    echo "tropar=cat /storage/9016-4EF8/myfiles/tropar.txt">>/storage/emulated/0/t-ui/alias.txt
    echo "ttm =sh /storage/emulated/0/ttm %
">>/storage/emulated/0/t-ui/alias.txt
    echo "ttm -p=search -u https://github.com/M4dGun/t-ui_themes">>/storage/emulated/0/t-ui/alias.txt


print_end