#!/?/bin/sh

SCRIPTNAME=${0##*/}

line="----------------------------------------------"
TXTDIR="/storage/emulated/0/t-ui/script_texts"
FILE="/storage/emulated/0/t-ui/script_texts/optina.txt"


print_header() {

    printf "%s\n" \
              $line \
              "          Молитва оптинских старцев" \
              " "
}
 
   
big_letters() {
    echo "$string" | awk '{print toupper($0)}'
}

      
print_file () {

b="."
    cd $TXTDIR
while IFS= read -r string;do
a=`echo $string | tail -c 3`
    if [ "$x" = 1 ]
        then big_letters
        else echo "$string"
    fi    
    if [ "$a"="$b" ]
        then printf " %s\n"
    fi
done < optina.txt
    printf "%s\n" $line
    exit 0
}


## Choosing a print option
case "$1" in
        1)
            x=1
            print_header
            print_file
            ;;
        *)
            x=0
            print_header
            print_file
            ;;
esac


