#!/bin/sh

## Author  	: AGCH
## Github  	: @alexgeorgchist
## 17.01.2023
SCRIPTNAME=${0##*/}

TXTDIR="/storage/emulated/0/t-ui/script_texts"
FILE="/storage/emulated/0/t-ui/script_texts/pokoypsaltir.txt"
LINE=" =================================="
POKOY="Псалтирь по усопшим"


print_header () {
    printf "%s\n" \
           " " \
           " " \
           "$LINE" \
           "        $POKOY" \
           "$LINE"
}
   
big_letters() {
echo " $string" | awk '{print toupper($0)}'
}
           

print_file () {
b="."
c=":"
cd $TXTDIR
while IFS= read -r string;do
a=`echo $string | tail -c 2`

if [ "$x" = 1 ]
then big_letters
else echo " $string"
fi

if [ "$a" = "$c" ] || [ "$a" = "$b" ]
    then printf " \n"
fi
done < pokoypsaltir.txt
#    printf "$LINE"
    exit 0
}


## Choosing a print option
case "$1" in
        1)
            x=1
            print_header
            print_file
            ;;
        *)
            x=0
            print_header
            print_file
            ;;
esac

