#!/bin/sh

## MM - My Manager
## Author  	: AGCH ( thanks to EMA,Dedrabbit and guys )
## Github  	: @alexgeorgchist

##################################
##                              ##
##       ##   ##  ##   ##       ##
##   #   ### ###  ### ###   #   ##
##  ###  ## # ##  ## # ##  ###  ##
##   #   ##   ##  ##   ##   #   ##
##       ##   ##  ##   ##       ##
##                              ##
##################################

SCRIPTNAME=${0##*/}

## DIRECTORIES
HOME="/storage/emulated/0"
#TUIDIR="/storage/emulated/0/t-ui"
TUI="t-ui"
THEMES_LIST=("my_nethunter.zip" "my_sharif.zip" "aqua.zip" "gf45.zip" "2022.zip" "yellow.zip" "big_bold.zip")


## LINKS
LINK="https://github.com/alexgeorgchist/my_tui/raw/main/database"
#LINKSCRIPT="https://github.com/alexgeorgchist/my_tui/edit/main/database/theme_manager/mm"

theme_1="my_nethunter"
theme_2="my_sharif"
theme_3="aqua"
theme_4="gf45"
theme_5="2022"
theme_6="yellow"
theme_7="big_bold"
ZP=".zip"


## LABELS
print_header () {
    printf "%s\n" \
        "#######################################" \
        "#         $SCRIPTNAME - УСТАНОВЩИК ТЕМ         #" \
        "#######################################" 
	   printf " \n"
}

print_end () {
    printf " \n"
    printf "%s\n" \
        "#######################################"\
        "      $SCRIPTNAME - Тема «$CHOSEN_THEME»        "\
        "  установлена.  ПЕРЕЗАГРУЗИТЕ  «T_UI».         " \
        "#######################################"
    
    printf " \n\n"
}

##SUBBLOCKS


show_help(){
 
	padding=-14
	print_header
	printf "%s\n" \
	    " Как пользоваться:"\
        " sh $SCRIPTNAME [-h, --help]"\
        "       [-l, --list]"\
        "       [1,2 или 3... до 7]"\
        "       [-v, --version]"

		
    printf " \n"
    printf "  %${padding}s %s\n" \
	    "От 1 до 7" "Установка темы n.1 (2,3 и т.д.)" \
        "-l, --list" "Показать доступные темы" \
        "-h, --help" "Справка по использованию" \
        "-v, --version" "Версия программы"
        
	printf " \n"
	printf "  %${padding}s %s\n" \
        "Примечание:" \
        "Набрать sh mm далее выбранный аттрибут через пробел."
        
	exit 1
}

show_theme(){

	echo "Скрипт установки темы T-UÍ"
printf " \n"
echo " ##################################"
echo " ##                              ##"
echo " ##       ##   ##  ##   ##       ##"
echo " ##   #   ### ###  ### ###   #   ##"
echo " ##  ###  ## # ##  ## # ##  ###  ##"
echo " ##   #   ##   ##  ##   ##   #   ##"
echo " ##       ##   ##  ##   ##       ##"
echo " ##                              ##"
echo " ##################################"
	padding=-20
	printf " \n"
	printf "%s\n" \
	    " ---------------------------------- "\
        "             СПИСОК ТЕМ         "
    printf " \n"
    printf "  %${padding}s %s\n" \
	    "1.$theme_1" \
		"2.$theme_2" \
		"3.$theme_3" \
		"4.$theme_4" \
		"5.$theme_5" \
  "6.$theme_6" \
  "7.$theme_7"

	printf "%s\n \n " \
	    " ---------------------------------- "
	    
	printf "%s\n " \
		":: Для установки набрать: sh mm номер" \
		"   Пример: sh mm 2 [ загрузка my_sharif] " \
	    " " \
		":.:   sh mm -h    ---- вызов справки"
		
    exit 1
}

version(){
	echo " T-ui Theme Manager"
	printf " \n"
	echo "Версия программы  v.1.03 "
	
	exit 1
}



## [123456789]|10|11|12|13)
## index=$(($1-1))   ##CHOSEN_THEME="{THEME_LIST[$index]}"


case "$1" in
    [1234567])
	index=$(($1 - 1))
	CHOSEN_THEME="${THEMES_LIST[$index]}"
        ;;
    -l|--list|%)
        show_theme
        ;;  
    -v|--version)
        version
        ;;
    -h|--help)
		show_help
        ;;
    *)
        printf " :: Недействительный аттрибут.\n Наберите sh mm -h для справки \n"
        exit 1
        ;;
esac




## START

    print_header
    cd $HOME
    rm -rf $TUI #удаляю папку T-UI в корне
    printf "\n\n :.:  Удаление папки t-ui ...  :.:"; sleep 1.0
    printf "\n\n ... успешно.  "; sleep 1.5
    printf "\n\n :.:  Скачиваю файл установки из репозитория   :.:"; sleep 2.0
    printf "\n\n ... успешно.  "; sleep 1.5
    printf "\n\n :.:  Распаковываю архив  :.: \n\n"; sleep 2.0
    
    cd $HOME && curl -LJO $LINK/$CHOSEN_THEME #скачиваю с GitHub xxx?.zip
    
#    cd $HOME && unzip -o $CHOSEN -d $HOME
   unzip -d $HOME -q $CHOSEN_THEME
   rm -rf $CHOSEN_THEME
   printf "\n\n :.:  Успешно  :.: \n\n"
    
print_end
