#!/bin/sh


## My Theme Manager
## Author  	: AGCH ( thanks to EMA,Dedrabbit and guys )
## Github  	: @alexgeorgchist
###########################
##                       ##
##  #   #  #   #  #   #  ##
##  ## ##  ##  #  #   #  ##
##  # # #  # # #  #####  ##
##  #   #  #  ##  #   #  ##
##  #   #  #   #  #   #  ##
##                       ##
###########################

SCRIPTNAME=${0##*/}

## DIRECTORIES
#cd $HOME && mkdir TEMP
#TEMP="/storage/emulated/0/TEMP"
#TEMPF="/storage/emulated/0/TEMP/my_tui-main"
HOME="/storage/emulated/0"
TUIDIR="/storage/emulated/0/t-ui"
TUI="t-ui"
THEME="my_nethunter"
ZP=".zip"

##LINKS
LINK="https://github.com/alexgeorgchist/my_tui/raw/main/database/my_nethunter.zip"

## LABELS

print_header () {
    printf "%s\n" \
        "#######################################"\
        "#  $SCRIPTNAME - УСТАНОВКА ТЕМЫ $THEME #"\
        "#######################################"
        printf " \n"
}

print_end () {
    printf " \n"
    printf "%s\n" \
        "#######################################"\
        "#    $SCRIPTNAME - Тема «$THEME»       #"\
        "#   установлена. Перезагрузите T_UI   #"\
        "#######################################"
    
    printf " \n"
}

## START
    print_header
cd $TUIDIR && cp alias.txt $HOME #сохраняю мой алиас в корень
cd $HOME && rm -rf $TUI #удаляю папку T-UI в корне
    printf " \n"
    printf "Удаление папки t-ui --- Успешно." \
    printf " \n"
sleep 1

cd $HOME && curl -L -O $LINK #скачиваю с GitHub mynethunter.zip
unzip -d $HOME -o $THEME$ZP

## 
#cd $HOME && rm -rf ?
cd $HOME && mv -f alias.txt $TUI #возвращаю мой алиас в T-UI
print_end



