#!/bin/sh

## My Theme Manager
## Author  	: AGCH ( thanks to EMA,Dedrabbit and guys )
## Github  	: @alexgeorgchist
###########################
##                       ##
##  #   #  #   #  #   #  ##
##  ## ##  ##  #  #   #  ##
##  # # #  # # #  #####  ##
##  #   #  #  ##  #   #  ##
##  #   #  #   #  #   #  ##
##                       ##
###########################

SCRIPTNAME=${0##*/}

## DIRECTORIES
HOME="/storage/emulated/0"
#TUIDIR="/storage/emulated/0/t-ui"
TUI="t-ui"
THEME="my_nethunter"
ZP=".zip"

##LINKS
LINK="https://github.com/alexgeorgchist/my_tui/raw/main/database/my_nethunter.zip"
#LINKSCRIPT="https://github.com/alexgeorgchist/my_tui/edit/main/database/theme_manager/mnh"

## LABELS
print_header () {
    printf "%s\n" \
        "#######################################"\
        "#  $SCRIPTNAME - УСТАНОВКА ТЕМЫ $THEME  #"\
        "#######################################"
}

print_end () {
    printf " \n"
    printf "%s\n" \
        "#######################################"\
        "#     $SCRIPTNAME - Тема «$THEME»       #"\
        "#   установлена. Перезагрузите T_UI   #"\
        "#######################################"
    
    printf " \n\n"
}

## START SCRIPT

    print_header
cd $HOME && rm -rf $TUI #удаляю папку T-UI в корне
    printf "\n\n :.:  Удаление папки t-ui   :.:"; sleep 2.0
    printf "\n\n :.:  Успешно  :.:"; sleep 1.5
    printf "\n\n :.:  Скачиваю файл установки из репозитория   :.:"; sleep 1.5
    printf "\n\n :.:  Распаковываю архив  :.: \n\n"; sleep 1.5
    
cd $HOME && curl -L -O $LINK #скачиваю с GitHub mynethunter.zip
    
    cd $HOME && unzip -d $HOME -q $THEME$ZP
    cd $HOME && rm -rf $THEME$ZP
    printf "\n\n :.:  Успешно  :.: \n\n"
print_end
## END
