#!/bin/sh

## My Theme Manager
## Author  	: AGCH ( thanks to EMA,Dedrabbit and guys )
## Github  	: @alexgeorgchist
###########################
##                       ##
##  #   #  #   #  #   #  ##
##  ## ##  ##  #  #   #  ##
##  # # #  # # #  #####  ##
##  #   #  #  ##  #   #  ##
##  #   #  #   #  #   #  ##
##                       ##
###########################

SCRIPTNAME=${0##*/}

## DIRECTORIES
#cd $HOME && mkdir TEMP
#TEMP="/storage/emulated/0/TEMP"
#TEMPF="/storage/emulated/0/TEMP/my_tui-main"
HOME="/storage/emulated/0"
TUIDIR="/storage/emulated/0/t-ui"
TUI="t-ui"
THEME="my_nethunter"
ZP=".zip"

##LINKS
LINK="https://github.com/alexgeorgchist/my_tui/raw/main/database/my_nethunter.zip"
LINKSCRIPT="https://github.com/alexgeorgchist/my_tui/edit/main/database/theme_manager/mnh"

## LABELS

print_header () {
    printf "%s\n" \
        "#######################################"\
        "#  $SCRIPTNAME - УСТАНОВКА ТЕМЫ $THEME  #"\
        "#######################################"
        printf " \n"
}

print_end () {
    printf " \n"
    printf "%s\n" \
        "#######################################"\
        "#     $SCRIPTNAME - Тема «$THEME»       #"\
        "#   установлена. Перезагрузите T_UI   #"\
        "#######################################"
    
    printf " \n"
}

## START
    print_header
#cd $TUIDIR && mv -f alias.txt $HOME #сохраняю мой алиас в корень
cd $HOME && rm -rf $TUIDIR #удаляю папку T-UI в корне
    printf " \n"
    printf " \n"
    printf "::.:: Удаление папки t-ui --- Успешно ::.::" \
    printf " \n"
    printf " \n"

cd $HOME && curl -L -O $LINK #скачиваю с GitHub mynethunter.zip
    printf " \n"
    printf " \n"
    printf "::.:: Распаковываю архив ::.::"
    printf " \n"
    printf " \n"
unzip -d $HOME -q $THEME$ZP

cd $HOME && curl -L -O $LINKSCRIPT #скачиваю с GitHub mnh скрипт

## 
#cd $HOME && rm -rf nethunter.zip
#cd $HOME && mv -f alias.txt $TUIDIR #возвращаю мой алиас в T-UI
print_end









