#!/bin/sh

## MM - My Manager
## Author  	: AGCH ( thanks to EMA,Dedrabbit and guys )
## Github  	: @alexgeorgchist

##################################
##                              ##
##       ##   ##  ##   ##       ##
##   #   ### ###  ### ###   #   ##
##  ###  ## # ##  ## # ##  ###  ##
##   #   ##   ##  ##   ##   #   ##
##       ##   ##  ##   ##       ##
##                              ##
##################################

SCRIPTNAME=${0##*/}

HOME="/storage/emulated/0"
TUI="t-ui"
ZP=".zip"

## LINKS
LINK="https://github.com/alexgeorgchist/my_tui/raw/main/database/themes_zip_arhive"
SCRIPT="https://github.com/alexgeorgchist/my_tui/raw/main/database/scripts/script.zip"
LOGOS="https://github.com/alexgeorgchist/my_tui/raw/main/database/scripts/logos.zip"
ASCII="https://github.com/alexgeorgchist/my_tui/raw/main/database/scripts/ascii.zip"

##  GET THEME LIST
cd $HOME && curl -o list.txt -s https://raw.githubusercontent.com/alexgeorgchist/my_tui/main/database/theme_list.txt
ppp=list.txt
THEME_LIST=(`cat "$ppp"`)
LIMIT=${#THEME_LIST[@]} #Number of topics in the array list
rm -rf $ppp

##=========================================

print_header_mmpic () {
    printf " \n"
    cat $HOME/$TUI/ascii//mmpic.txt
}


print_end () {
    printf " \n"
    printf "%s\n" \
        "========================================"\
        "      $SCRIPTNAME - Тема «$CHOSEN_THEME»        "\
        "  установлена.  ПЕРЕЗАГРУЗИТЕ  «T_UI».         " \
        "=============== THE END ================"
    
    printf " \n\n"
}


##SUBBLOCKS

show_help(){
 
	padding=-14
	print_header
	printf "%s\n" \
	    " :.: Как пользоваться:"\
        "     $SCRIPTNAME [-h, --help]"\
        "        [-l, --list]"\
        "        [1,2 или 3... до $LIMIT]"\
        "        [-v, --version]"

		
    printf " \n"
    printf "  %${padding}s %s\n" \
	    "От 1 до $LIMIT" "Установка темы n.1 (2,3 и т.д.)" \
        "-l, --list" "Показать доступные темы" \
        "-h, --help" "Справка по использованию" \
        "-v, --version" "Версия программы"
        
	printf " \n"
	printf "  %${padding}s %s\n" \
        " :.: Примечание:" \
        " Набрать mm далее выбранный аттрибут через пробел."
        
	exit 1
}


show_theme(){

    print_header_mmpic
    sleep 0.5
    padding=-20
	printf " \n"
	printf "%s\n" \
	    "  ---------------------------------- "\
        "         СПИСОК ДОСТУПНЫХ ТЕМ:         "

VAR=1 # Number of topics in the array list LIMIT=${#THEME_LIST[@]}
while [ "$VAR" -le "$LIMIT" ] # <=
do
    echo "   $VAR. ${THEME_LIST[$VAR-1]}"
    VAR=`expr $VAR + 1` # Allowed VAR=$(($VAR+1))
done

	printf "%s\n \n " \
	    "  ---------------------------------- "    
	sleep 0.5
	printf "%s\n " \
		" :.: Для установки набрать: mm номер" \
		"     Пример: mm 5 [ загрузка yellow ] " \
	    " " \
		" :.: mm -h    -- вызов справки"
		
    exit 1
}


version(){
	printf "%s\n" \
	          " " \
              " :.: $SCRIPTNAME - My Manager ( themes for t-ui )" \
	          " :.: Версия программы  v.1.09 от 03.05.22 "
	
	exit 1
}


## index=$(($1-1))   ##CHOSEN_THEME="{THEME_LIST[$index]}"

case "$1" in
    [1-$LIMIT])
	index=`expr $1 - 1` # Allowed index=$(($1-1))
	CHOSEN_THEME="${THEME_LIST[$index]}"
        ;;
    -l|--list|%)
        show_theme
        ;;  
    -v|--version)
        version
        ;;
    -h|--help)
		show_help
        ;;
    *)
        printf " :.: Недействительный аттрибут.\n";sleep 1.0
        printf " \n"    
        show_help
        exit 1
        ;;
esac



## START PROG HERE

    print_header_mmpic

    printf "\n\n :.:  Удаление папки t-ui ...  :.:"
    cd $HOME && rm -rf $TUI
    printf "\n\n ...  УСПЕШНО.  "

    printf "\n\n :.:  Скачиваю файл установки $CHOSEN_THEME$ZP из репозитория ...   :.:"
    cd $HOME && curl -LJO -s $LINK/$CHOSEN_THEME$ZP
    printf "\n\n ...  УСПЕШНО.  "

    printf "\n\n :.:  Распаковываю архив  :.: \n\n"
    unzip -d $HOME -q $CHOSEN_THEME$ZP
    rm -rf $CHOSEN_THEME$ZP
    printf "\n\n ...  УСПЕШНО.  :.:"

    printf "\n\n :.:  Скачиваю и добавляю скрипты ascii,sysinfo и chwf   :.: \n\n"
    cd $HOME/$TUI && rm -rf script logos ascii
    cd $HOME/$TUI && curl -LJO -s $SCRIPT
    cd $HOME/$TUI && curl -LJO -s $LOGOS
    cd $HOME/$TUI && curl -LJO -s $ASCII
    unzip -q script.zip && unzip -q logos.zip && unzip -q ascii.zip
    rm -rf script.zip logos.zip ascii.zip
    printf "\n\n ...  УСПЕШНО.  :.:"

## Добавляю строки в alias.txt
    echo "mm =sh /storage/emulated/0/mm %">>/storage/emulated/0/t-ui/alias.txt
    echo "mm -p=search -u https://github.com/alexgeorgchist/my_tui/tree/main/database">>/storage/emulated/0/t-ui/alias.txt
    echo " memo =sh /storage/emulated/0/t-ui/script/mem %">>/storage/emulated/0/t-ui/alias.txt
    echo "sysinfo=sh /sdcard/t-ui/script/sysinfo %">>/storage/emulated/0/t-ui/alias.txt
    echo "chwf=sh /sdcard//t-ui/script/chwf %">>/storage/emulated/0/t-ui/alias.txt
    echo "aliases=cat /sdcard/t-ui/alias.txt">>/storage/emulated/0/t-ui/alias.txt
    echo "tropar=cat /storage/9016-4EF8/myfiles/tropar.txt">>/storage/emulated/0/t-ui/alias.txt
    echo "ttm =sh /storage/emulated/0/ttm %
">>/storage/emulated/0/t-ui/alias.txt
    echo "ttm -p=search -u https://github.com/M4dGun/t-ui_themes">>/storage/emulated/0/t-ui/alias.txt

print_end
