#!/bin/sh

## MM - My Manager
## Author  	: AGCH ( thanks to EMA,Dedrabbit and guys )
## Github  	: @alexgeorgchist

##################################
##                              ##
##       ##   ##  ##   ##       ##
##   #   ### ###  ### ###   #   ##
##  ###  ## # ##  ## # ##  ###  ##
##   #   ##   ##  ##   ##   #   ##
##       ##   ##  ##   ##       ##
##                              ##
##################################

SCRIPTNAME=${0##*/}

##DIRECTORIES
HOME="/storage/emulated/0"
TUIDIR="/storage/emulated/0/t-ui"
SCRIPTDIR="/storage/emulated/0/script"
ASCIIDIR="/storage/emulated/0/ascii"
LOGODIR="/storage/emulated/0/logo"

TUI="t-ui"
ZP=".zip"

## LINKS
LINK="https://github.com/alexgeorgchist/my_tui/raw/main/database/themes_zip_arhive"

##  GET THEME LIST
cd $HOME && curl -o list.txt -s https://raw.githubusercontent.com/alexgeorgchist/my_tui/main/database/theme_list.txt
ppp=list.txt
THEME_LIST=(`cat "$ppp"`)
LIMIT=${#THEME_LIST[@]} #Number of topics in the array list
rm -rf $ppp



print_header_mmpic() {

    printf " \n"
    cat $ASCIIDIR/mmpic.txt
    
}


print_end () {

    printf " \n"
    printf "%s\n" \
        "========================================"\
        "      $SCRIPTNAME - Тема «$CHOSEN_THEME»        "\
        "         успешно установлена.        " \
        "         Перезагрузите «T-UI» " \
        "=============== THE END ================"
    
    printf " \n\n"
    exit 1
    
}


##SUBBLOCKS

show_help() {

	padding=-14
	print_header_mmpic
	printf "%s\n" \
	    " :.: Как пользоваться:"\
        "     $SCRIPTNAME [-h, --help]"\
        "        [-l, --list]"\
        "        [1,2 или 3... до $LIMIT]"\
        "        [-v, --version]"

		
    printf " \n"
    printf "  %${padding}s %s\n" \
	    "От 1 до $LIMIT" "Установка темы n.1 (2,3 и т.д.)" \
        "-l, --list" "Показать доступные темы" \
        "-h, --help" "Справка по использованию" \
        "-v, --version" "Версия программы"
        
	printf " \n"
	printf "  %${padding}s %s\n" \
        " :.: Примечание:" \
        " Набрать mm далее выбранный аттрибут через пробел."
        
	exit 1
	
}


show_theme() {

    print_header_mmpic
    sleep 0.5
    padding=-20
	printf " \n"
	printf "%s\n" \
	    "  ---------------------------------- "\
        "         СПИСОК ДОСТУПНЫХ ТЕМ:         "

VAR=1 # Number of topics in the array list LIMIT=${#THEME_LIST[@]}
while [ "$VAR" -le "$LIMIT" ] # <=
do
    echo "   $VAR. ${THEME_LIST[$VAR-1]}"
    VAR=`expr $VAR + 1` # Allowed VAR=$(($VAR+1)) or let "VAR += 1"
done

	printf "%s\n \n " \
	    "  ---------------------------------- "    
	sleep 0.5
	printf "%s\n " \
		" :.: Для установки набрать: mm номер" \
		"     Пример: mm 5 [ загрузка yellow ] " \
	    " " \
		" :.: mm -h    -- вызов справки"
		
    exit 1
    
}


version() {

	printf "%s\n" \
	          " " \
              " :.: $SCRIPTNAME - My Manager ( themes for t-ui )" \
	          " :.: Версия программы  v.1.12 от 06.05.22 "
	
}





load_theme() {

    cd $HOME && rm -rf $TUI

    echo " :.: Процесс загрузки из репозитория"
    echo "     файл установки $CHOSEN_THEME$ZP:";sleep 0.5
    cd $HOME
    curl -LJO -s $LINK/$CHOSEN_THEME$ZP &&  echo "     - загрузка --> успешно" || echo "     - ошибка загрузки"
    
    echo "      Распаковка:";sleep 0.5
    unzip -d $HOME -q $CHOSEN_THEME$ZP &&  echo "     - распаковка --> успешно" || echo "     - ошибка распаковки"

    rm -rf $CHOSEN_THEME$ZP

}


additional_folders() {

SCRIPTFILE="https://github.com/alexgeorgchist/my_tui/raw/main/database/scripts/script.zip"
LOGOSFILE="https://github.com/alexgeorgchist/my_tui/raw/main/database/scripts/logos.zip"
ASCIIFILE="https://github.com/alexgeorgchist/my_tui/raw/main/database/scripts/ascii.zip"
 
    cd $TUIDIR && rm -rf script logos ascii
    echo " "
    echo " :.:  Добавление папок:";sleep 0.5
    cd $TUIDIR
    curl -LJO -s $SCRIPTFILE && echo "     - script.zip загрузка --> успешно" || echo "     - архив script.zip --- ошибка загрузки"
    curl -LJO -s $LOGOSFILE && echo "     - logos.zip  загрузка --> успешно" || echo "     - архив logos.zip  --- ошибка загрузки"
    curl -LJO -s $ASCIIFILE && echo "     - ascii.zip  загрузка --> успешно" || echo "     - архив ascii.zip  --- ошибка загрузки"
    
    echo "      Распаковка:";sleep 0.5
    unzip -q script.zip && echo "     - папка «script» --- успешно" || echo "     - «script» --- ошибка загрузки"
    unzip -q logos.zip && echo "     - папка «logos»  --- успешно" || echo "     - «logos» --- ошибка загрузки"
    unzip -q ascii.zip && echo "     - папка «ascii»  --- успешно" || echo "     - «ascii» --- ошибка загрузки"
    rm -rf script.zip logos.zip ascii.zip

}

add_aliases() {

## Add aliases in to alias.txt

    echo "mm =sh /storage/emulated/0/mm %">>$TUIDIR/alias.txt
    echo "mm -p=search -u https://github.com/alexgeorgchist/my_tui/tree/main/database">>$TUIDIR/alias.txt
    echo "sysinfo=sh /sdcard/t-ui/script/sysinfo %">>$TUIDIR/alias.txt
    echo "chwf=sh /sdcard//t-ui/script/chwf %">>$TUIDIR/alias.txt
    echo "aliases=cat /sdcard/t-ui/alias.txt">>$TUIDIR/alias.txt
    
    echo "ttm =sh /storage/emulated/0/ttm %">>$TUIDIR/alias.txt
    echo "ttm -p=search -u https://github.com/M4dGun/t-ui_themes">>$TUIDIR/alias.txt

}


add_memo() {

## Add memo script

MEMFILE="https://github.com/alexgeorgchist/my_tui/raw/main/database/scripts/mem.zip"

    echo " "
    echo " :.:  Добавление скрипта memo:";sleep 0.5
    cd $SCRIPTDIR
    curl -LJO -s $MEMFILE &&  echo "     - загрузка --> успешно" || echo "     - ошибка загрузки"
    unzip -q mem.zip &&  echo "     - распаковка --> успешно" || echo "     - ошибка распаковки"

    echo "memo =sh /storage/emulated/0/t-ui/script/memo %">>$TUIDIR/alias.txt
   
}


add_troppokoy(){

## Add tropar in to alias.txt

TROPPOKOYFILE="https://github.com/alexgeorgchist/my_tui/raw/main/database/scripts/troppokoy.zip"

    echo " "
    echo " :.:  Добавление скрипта troppokoy:";sleep 0.5
    cd $TUIDIR
    curl -LJO -s $TROPPOKOYFILE &&  echo "     - загрузка --> успешно" || echo "     - ошибка загрузки"
    unzip -q troppokoy.zip
    mv troppokoy $SCRIPTDIR &&  echo "     - распаковка --> успешно" || echo "     - ошибка распаковки"
    rm -rf troppokoy.zip

    echo "troppokoy=sh /storage/emulated/0/t-ui/script/troppokoy %">>$TUIDIR/alias.tx

}


add_6psalm() {

## Add 6psalm

PSALM="https://github.com/alexgeorgchist/my_tui/raw/main/database/scripts/6p.zip"

    echo " "
    echo " :.:  Добавление скрипта 6p:";sleep 0.5
    cd $TUIDIR
    curl -LJO -s $PSALM &&  echo "     - загрузка --> успешно" || echo "     - ошибка загрузки"
    unzip -q 6p.zip
    mv 6p $TUIDIR/script &&  echo "     - распаковка --> успешно" || echo "     - ошибка распаковки"
    rm -rf 6p.zip

    echo "6p=sh /storage/emulated/0/t-ui/script/6p %">>$TUIDIR/alias.txt

}


## index=$(($1-1))   ##CHOSEN_THEME="{THEME_LIST[$index]}"

case "$1" in
    [1-$LIMIT])
	index=`expr $1 - 1` # Allowed index=$(($1-1))
	CHOSEN_THEME="${THEME_LIST[$index]}"
        ;;
    -l|--list|%)
        show_theme
        ;;  
    -v|--version)
        version
        sleep 3.0 && echo " "
        show_help
        ;;
    -h|--help)
		show_help
        ;;
    *)
        printf " :.: Недействительный аттрибут.\n";sleep 1.0
        printf " \n"    
        show_help
        exit 1
        ;;
esac



## START PROG HERE

print_header_mmpic
load_theme
additional_folders
add_aliases
add_memo
add_troppokoy
add_6psalm
print_end
