#!/bin/sh

## MM - My Manager
## Author  	: AGCH
## Github  	: @alexgeorgchist

##################################
##                              ##
##       ##   ##  ##   ##       ##
##   #   ### ###  ### ###   #   ##
##  ###  ## # ##  ## # ##  ###  ##
##   #   ##   ##  ##   ##   #   ##
##       ##   ##  ##   ##       ##
##                              ##
##################################

SCRIPTNAME=${0##*/}

home="/storage/emulated/0"
link="https://raw.githubusercontent.com/alexgeorgchist/my_tui/main/database/mm_releases/mm"
line1="============================================="
line2="---------------------------------------------"
padding=23



head_script() {
    printf " %s\n" \
              "$line1" \
              "• Привет, Сашечка." \
              "• Программа $SCRIPTNAME обновит скрипт mm" \
              "$line2"
    sleep 1.5
}


give_me() {       
cd $home
if [ -f $home/mm ];then rm -rf mm
fi
    printf " %${padding}s %s\n" \
              "Заменяемый файл удален" "           ▁ ▂ ▃ ▄ 32% "
    sleep 1.5
    printf " %${padding}s %s\n" \
              " " " " \
              "Загружаю               " "      ▁ ▂ ▃ ▄ ▅ ▆ 68%"
    sleep 1.5

curl -o mm -s $link

    printf " %${padding}s %s\n" \
              " " " "\
              "Обновление загружено"  "    ▁ ▂ ▃ ▄ ▅ ▆ ▇ █ 100%" \
              " "
    sleep 0.5
              
#a=`sed -n '20p' < mm`
#b=`sed -n '21p' < mm`
#   printf " %s\n" $a \
#                          $b \
#                          $line1

}


goto_mm() {                           
## Start mm script
if [ $? = 0 ] && [ -f $home/mm ]
    then  sh ./mm -v
fi
    
if [ $? = 77 ] # in the mm script show_theme exit 77
    then printf " %s\n" \
                       "$line2" \
                       "• Конец программы $SCRIPTNAME"
fi
}


end_script() {
if [ $? != 0 ]
    then printf " %s\n" "Что-то не то, надо разобраться"
    else  printf "%s\n" $line1
fi
exit 0
}

head_script
give_me
goto_mm
end_script
